add whywaita
herp-inc/engineering-careers pull request #48
Opened 2020-10-05 17:31 UTC by whywaita

2020-10-07 04:05 UTC, ryota-ka requested changes

2020-10-07 04:05 UTC, ryota-ka commented on docs/members.md
> +
メンバは原則入社日昇順で並べてるので，ゲルゲさんの上に書いちゃってください 🙏

2020-10-08 12:59 UTC, whywaita commented on docs/members.md
> +
fixed! https://github.com/herp-inc/engineering-careers/pull/48/commits/85e6b9ae2faca9220e0207971a02c1fede327ef7

2020-10-08 13:00 UTC, ryota-ka approved these changes
よさそう！
squash して merge しちゃってください 🙏

2020-10-08 13:06 UTC, merged

2020-10-08 13:06 UTC, whywaita commented
🙏